// Code generated by MockGen. DO NOT EDIT.
// Source: internal/contracts/product_contracts.go
//
// Generated by this command:
//
//	mockgen -source=internal/contracts/product_contracts.go -destination=mocks/contracts/product_repo_contract_mock.go -exclude_interfaces=ProductServiceContract
//

// Package mock_contracts is a generated GoMock package.
package mock_contracts

import (
	domain "product_service_saga/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductRepoContract is a mock of ProductRepoContract interface.
type MockProductRepoContract struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepoContractMockRecorder
	isgomock struct{}
}

// MockProductRepoContractMockRecorder is the mock recorder for MockProductRepoContract.
type MockProductRepoContractMockRecorder struct {
	mock *MockProductRepoContract
}

// NewMockProductRepoContract creates a new mock instance.
func NewMockProductRepoContract(ctrl *gomock.Controller) *MockProductRepoContract {
	mock := &MockProductRepoContract{ctrl: ctrl}
	mock.recorder = &MockProductRepoContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepoContract) EXPECT() *MockProductRepoContractMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockProductRepoContract) FindByID(id int) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProductRepoContractMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProductRepoContract)(nil).FindByID), id)
}

// GetProducts mocks base method.
func (m *MockProductRepoContract) GetProducts() ([]*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts")
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockProductRepoContractMockRecorder) GetProducts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockProductRepoContract)(nil).GetProducts))
}
