// Code generated by MockGen. DO NOT EDIT.
// Source: internal/kafka/publisher.go
//
// Generated by this command:
//
//	mockgen -source=internal/kafka/publisher.go -destination=internal/mocks/kafka/publisher_mock.go
//

// Package mock_kafka is a generated GoMock package.
package mock_kafka

import (
	context "context"
	reflect "reflect"

	kafka "github.com/segmentio/kafka-go"
	gomock "go.uber.org/mock/gomock"
)

// MockIKafkaWriter is a mock of IKafkaWriter interface.
type MockIKafkaWriter struct {
	ctrl     *gomock.Controller
	recorder *MockIKafkaWriterMockRecorder
	isgomock struct{}
}

// MockIKafkaWriterMockRecorder is the mock recorder for MockIKafkaWriter.
type MockIKafkaWriterMockRecorder struct {
	mock *MockIKafkaWriter
}

// NewMockIKafkaWriter creates a new mock instance.
func NewMockIKafkaWriter(ctrl *gomock.Controller) *MockIKafkaWriter {
	mock := &MockIKafkaWriter{ctrl: ctrl}
	mock.recorder = &MockIKafkaWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKafkaWriter) EXPECT() *MockIKafkaWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIKafkaWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIKafkaWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIKafkaWriter)(nil).Close))
}

// WriteMessages mocks base method.
func (m *MockIKafkaWriter) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessages indicates an expected call of WriteMessages.
func (mr *MockIKafkaWriterMockRecorder) WriteMessages(ctx any, msgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, msgs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockIKafkaWriter)(nil).WriteMessages), varargs...)
}
